# Generated by Django 2.2.14 on 2020-07-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('school_name', models.CharField(max_length=60)),
                ('tenth_mark', models.IntegerField()),
                ('twelth_mark', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_num', models.IntegerField()),
            ],
        ),
    ]
