# Generated by Django 2.2.14 on 2020-07-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200712_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('1', 'accept'), ('2', 'reject')], default='2', max_length=30),
        ),
    ]
