# Generated by Django 2.2.14 on 2020-07-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20200712_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.BooleanField(choices=[(True, 'accept'), (False, 'reject')], default=False),
        ),
    ]
