# Generated by Django 2.2.14 on 2020-07-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20200713_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(default='reject', max_length=30),
        ),
    ]
