# Generated by Django 2.2.14 on 2020-07-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20200713_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.BooleanField(choices=[(True, 'accept'), (False, 'reject')]),
        ),
    ]
